// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9OFRtP5gE9Ni9_GDA60XcPCVHmtdNZs0',
    appId: '1:254435245019:web:5db3c6d7aaba74937e05fe',
    messagingSenderId: '254435245019',
    projectId: 'e-commerce-flower-app',
    authDomain: 'e-commerce-flower-app.firebaseapp.com',
    storageBucket: 'e-commerce-flower-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMUEJNW0p6nL7zyCQt_dpB53izvjWVBAM',
    appId: '1:254435245019:android:79242fe904917b217e05fe',
    messagingSenderId: '254435245019',
    projectId: 'e-commerce-flower-app',
    storageBucket: 'e-commerce-flower-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyDHlc7zXsYyEDrAbtH9XjXBWynmRGK30',
    appId: '1:254435245019:ios:2fa0349c23ec5f8b7e05fe',
    messagingSenderId: '254435245019',
    projectId: 'e-commerce-flower-app',
    storageBucket: 'e-commerce-flower-app.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyDHlc7zXsYyEDrAbtH9XjXBWynmRGK30',
    appId: '1:254435245019:ios:2fa0349c23ec5f8b7e05fe',
    messagingSenderId: '254435245019',
    projectId: 'e-commerce-flower-app',
    storageBucket: 'e-commerce-flower-app.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9OFRtP5gE9Ni9_GDA60XcPCVHmtdNZs0',
    appId: '1:254435245019:web:18609023a55a8f4e7e05fe',
    messagingSenderId: '254435245019',
    projectId: 'e-commerce-flower-app',
    authDomain: 'e-commerce-flower-app.firebaseapp.com',
    storageBucket: 'e-commerce-flower-app.firebasestorage.app',
  );
}
